accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [ 
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
   
   
]

core/urls.py
from django.urls import path
from . import views

app_name= 'core'

urlpatterns = [
    path('',views.home,name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('products/',include('product.urls',namespace='product')),
    path('store/',include('store.urls',namespace='store')),
    path('',include('core.urls',namespace='core')),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from datetime import datetime
from email.policy import default
from sqlite3 import Date
from turtle import mode
from winreg import ConnectRegistry
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from django.utils.text import slugify

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,related_name ='signup',on_delete=models.CASCADE,verbose_name=_('user'))
    country = CountryField()
    location = models.CharField(max_length=100,default='',verbose_name=_('Location'))
    phone_number = models.CharField(max_length=15,verbose_name=_('Phone Number'))
    image = models.ImageField(upload_to='Images_profiles/%y/%m/%d',blank=True,null=True,verbose_name=_('Image'))
    join_date = models.DateTimeField(default=datetime.now,verbose_name=_('Date'))
    slug = models.SlugField(blank=True,null=True)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return str(self.user)

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.user, allow_unicode=True)
    #     super(Profile,self).save(*args,**kwargs)

    # def get_absolute_url(self):
    #     return reverse("profile:edit_profile", kwargs={"slug": self.slug})



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class ProfileEdit(models.Model):
    profile = models.OneToOneField(Profile,related_name ='edit_profile',on_delete=models.CASCADE,verbose_name=_('Profile'))
    image = models.ImageField(upload_to='Images_profiles/%y/%m/%d',blank=True,null=True,verbose_name=_('Image'))
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    country = CountryField()
    location = models.CharField(max_length=100,default='',verbose_name=_('Location'))
    phone_number = models.CharField(max_length=15,verbose_name=_('Phone Number'))

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,ProfileEdit

class SignForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['country','location','phone_number','image']
        

# class ProfileEditForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = '__all__'
#         excude = ('username',)
        

accounts/views.py
from django.shortcuts import render
from .forms import SignForm ,UserForm ,ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Profile

# Create your views here.

def signup(request):
    if request.method=='POST':
        form = SignForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')

    else :
        form = SignForm()

    return render(request,'registration/signup.html',{'form':form})


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {'profile':profile}

    return render(request,'accounts/profile.html',context)

@login_required
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileForm = ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid():
            userform.save()
            profileForm = profileForm.save(commit=False)
            profileForm.user = request.user
            profileForm.save()
            return redirect(reverse('accounts:profile'))

    else :
        userform=UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
        context = {'userform':userform,'profileform':profileform}

    return render(request,'accounts/edit_profile.html',context)

accounts/templates/accounts/edit_profile.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>XSTORE</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <br>
  <br>
  <br>
  <br> 
{% include 'navbar.html' %}

    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit Your Profile </h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <br>
    <br>

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto"> 
                    
                    
                    <div class="apply_job_form white-bg">
                      
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}

                            
                            <input class="boxed-btn3 w-100" type="submit" value="Save">
                            
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

{% include 'footer.html' %} 

accounts/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>XSTORE</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
    .pro{
      text-align: center;
      background-color: #fff;
      display: inline-block !important;
      float: right;
      margin-left: 450px;
      max-width: 100%;
      height: 400px;
      padding: 50px;
      margin-top: -370px;
      color:rgb(16, 60, 61);
    
    }
    .inp{
  
      background-color: #fff;
      border-radius: 5px;
      float: right;
      margin-top: -250px;
      text-align: center;
      
      margin-right: -470px;
      width:150px;
      height: 30px;
      background-color: #6a11cb;
      
      color: #fff;
    
    }
    .inp:hover{
      background-color: #44006b;
    }
  </style>
</head>

<body>

  <!-- Navbar -->
  <br>
  <br>
  <br>
  <br> 
{% include 'navbar.html' %}



<hr class="mt-0 mb-4">
<div class="container mb-4">
    <div class="row gutters">
        <div class="col-md-12 ">

            <div class="card h-100">
                <div class="card-body">
                    <div class="account-settings ">
                        <div class="user-profile">
                            <div class=" col-md-4">
                              {% if profile.image %}
                              <img src="{{ profile.image.url }}" class=" img-fluid" alt="...">
                              {% else %}
                              <img src="{% static 'img/images.jpg'%}" class="img-fluid" alt="...">
                              {% endif %}
                            </div>

                            <div class="pro col-md-6">
                              
                                <h1 class="user-name">Name : {{profile.user.first_name}} {{profile.user.last_name}}</h1>
                                <hr >
                                <h3 class=" user-email">Your Email :{{profile.user.email}}</h3>
                                <hr >
                                <h2>Phone Number :+{{profile.phone_number}}</h2>
                                <hr >
                            </div>
                        </div>
                        <div class="about col-md-10 mt-3">
                            <h2></h2>
                            <p></p>
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <div class=" col-md-4 mt-5">
                        <a class="inp col-md-6 " type="submit"  href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                    </div>
                </div>
                </div>
            </div>

        </div>
    </div>
    </div>
</div>

{% include 'footer.html' %}
</html>